### ISSUE TITLE
Atom Crashes whenever I type anything

### ISSUE THREAD

**Issue by astrale-sharp** [PrestonKnopp/language-gdscript#33] opened 2020-04-14 18:14 UTC
Step to induce the crash:

open atom from godot (having external checked and flags = {file}:{line}
the text appear correctly highlited, but if you type anything or try to modificate the code, atom crashes

thank you!

EDIT: typing new line is okay

**Comment by PrestonKnopp** [comment] 2020-04-15 00:33
Hey, I can't reproduce this. Does it crash when you open Atom manually with the gdscript file?

Are there any errors in the dev tools console? You can open the dev tools with: `Ctrl-Shift-I`.

Quick tip: When opening from Godot does work you can set the flags to `{file}:{line}:{col}`.

**Comment by astrale-sharp** [comment] 2020-04-15 07:54
Hey,
It does crash when you open manually with godot open or godot closed !
console before is linked as a .png below

![atomcrash_before_typing](https://user-images.githubusercontent.com/53686698/79312361-10b0bd80-7eff-11ea-9915-96f91196732e.png)


it crashed before anything new gets printed in the console 

Thanks again!

**Comment by PrestonKnopp** [comment] 2020-04-15 20:51
I'm not sure why it's crashing. 

Can you provide the output of the command `atom --version; apm --version`?

First, try running atom in safe mode: `atom --safe` and verify that it does work without packages.

After that can you try [clearing save state](https://flight-manual.atom.io/hacking-atom/sections/debugging/#clearing-saved-state) and if that doesn't work try [with factory defaults](https://flight-manual.atom.io/hacking-atom/sections/debugging/#reset-to-factory-defaults) and just install lang-gdscript?

Lastly, if the above doesn't shed any light can you attach the most recent crash log found in `/tmp/Atom\ Crashes`.

**Comment by astrale-sharp** [comment] 2020-04-16 10:07
sure thing : 
atom --version; apm --version :
#-----------------#
Atom    : 1.45.0
Electron: 4.2.7
Chrome  : 69.0.3497.128
Node    : 10.11.0
apm  2.4.3
npm  6.2.0
node 10.2.1 x64
atom 1.45.0
python 2.7.17
git 2.17.1
#-----------------#
Atom works just fine in safe mode!
I moved ./atom to ./atom.bkp (the only two package i have being lang_gdscript and  atom-ide-ui
 and Hydrogen
with only lang_gdscript installed:
It works fine ! no crash whatsoever! can edit files, with Godot opened or closed!
if i add atom-ide-ui:
It still works ! (btw it works so well, i was really eager to test that, it is SO GREAT to be able to code in atom)
as far as im concerned there is no more problem, i dont really understand why it works now, i'll let you close the issue if you agree with me, otherwise i can do some more test
with hydrogen:
It still works Oo, i dont understand my life but it seems like its all working ? Anyway thanks a lot for your help and let me now if i can help!

**Comment by PrestonKnopp** [comment] 2020-04-16 19:54
Awesome, I'm glad it's working and thank you so much for testing. I have no idea why it was crashing, so I'll close this issue.

**Closed by PrestonKnopp** 2020-04-16 19:54 UTC
