### ISSUE TITLE
Package broken when used with godot 3.2.2

### ISSUE THREAD

**Issue by jebedaia360** [PrestonKnopp/language-gdscript#36] opened 2020-07-04 18:36 UTC
On both windows 10 x64 and Ubuntu 20.04 x64.
After I update godot to new version 3.2.2.
Atom doesn't see godot's langue server - ports match in atom and godot editor.
But legacy (tree-sitter) autocomplete doesn't work either.

**Comment by PrestonKnopp** [comment] 2020-07-06 05:48
Hey thanks for posting this issue. This should now be fixed with version 6.0.0.

**Comment by jebedaia360** [comment] 2020-07-07 12:38
I will check today if it works.

**Comment by jebedaia360** [comment] 2020-07-07 13:28
I try to update and get this:
```
EPERM: operation not permitted, unlink 'C:\Users\jerem\.atom\packages\lang-gdscript\node_modules\tree-sitter-gdscript\build\Release\tree_sitter_gdscript_binding.node'
```

**Comment by PrestonKnopp** [comment] 2020-07-07 19:35
I'm unable to reproduce the EPERM error on macOS and Ubuntu. It looks like `tree_sitter_gdscript_binding.node` file may be locked by something.

Can you try closing Atom, or any app that may possibly be locking the file, and then reinstalling from the command line:

```
apm uninstall lang-gdscript
apm install lang-gdscript
```

**Comment by jebedaia360** [comment] 2020-07-08 08:46
It work when I did:
```
apm uninstall lang-gdscript
apm install lang-gdscript
```
but when uninstalling I got something like this:
`Can delete lang-gdscript dir, because it can't found .../.atom/packages/lang-gdscript/package.json`
So I must delete this folder manually before reinstall.

**Comment by PrestonKnopp** [comment] 2020-07-10 04:16
Huh, that's strange. I wonder why that happened?

Thanks for testing the above. I don't think it's caused by lang gdscript so I'll close this issue.

**Closed by PrestonKnopp** 2020-07-10 04:16 UTC
